### ISSUE TITLE
Adapt to Mac OS

### ISSUE THREAD

**Issue by mdelaval** [mnh48/Aegisub-DiscordRPC#1]
I'm under the impression this plugin was developed on Windows but I'd like to use it on my Mac and I'm not exactly tech-savvy enough to figure it out myself, try as I might. I believe the core issue may be with the different installation folders, this is how it's organized on Mac: 

![Screen Shot 2021-01-20 at 2 49 44 PM](https://user-images.githubusercontent.com/40327571/105221246-3a9eac80-5b2f-11eb-8eb7-83ea120bddb7.png)

so a few more layers than Windows installation. I rotated the .dll file in every layer between the automation file and the app itself to no avail. When I open Aegisub with the files in place, I get this error message:

> 14:55:22: A script in the Automation autoload directory failed to load.
> Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
> 14:55:22: Failed to load Automation script '/Applications/Aegisub.app/Contents/SharedSupport/automation/autoload/discord-rpc.lua':
> Error initialising Lua script "discord-rpc.lua":
> 
> [string "/Applications/Aegisub.app/Contents/SharedSupp..."]:13: dlopen(libdiscord-rpc.dylib, 5): image not found

As I said, I'm quite new to this and took quite some time to research things but I'm still stuck. I understand if Mac is too different from Windows to adapt your existing plugin, thank you already for taking the time to read this. If you need any more information, please reach out and we can discuss it further.

**Comment by mnh48** [comment]
can you try to put the `discord-rpc.lua` file in `autoload` folder (exist in `automation` folder)?
delete the file `discord-rpc.dll` because that would not work in MacOS

then can you try to put this file `libdiscord-rpc.dylib` instead in place where you put `discord-rpc.dll` earlier?
the file is in this zip: [libdiscord-rpc.zip](https://github.com/mnh48/Aegisub-DiscordRPC/files/5845235/libdiscord-rpc.zip)

**Comment by mnh48** [comment]
if that works then I'll update the repo with that file, the file is actually from upstream rpc library
I just take it from `discord-rpc-osx.zip` off https://github.com/discord/discord-rpc/releases/tag/v3.4.0 (MIT license)

**Comment by mdelaval** [comment]
Thank you for replying so quickly, I tried the .dylib file in all the same places as before (2nd, 3rd, and 4th columns in the original post's screenshots) but the same error message persists.

**Comment by mnh48** [comment]
can you try to put it in same folder as the `discord-rpc.lua` itself and see if that works?

**Comment by mdelaval** [comment]
Just tried that and it was the same message again, same results again when i tried putting it in the `automation` folder.

**Comment by mnh48** [comment]
can you check what's the permission of the file? because I can't check the exact permission for mac file in windows
maybe there's something wrong with the permission itself

right click the file, click on 'get info', and see if "everyone" is on "read & write"?

**Comment by mnh48** [comment]
btw if I don't reply so soon, it means I went to sleep... because I didn't sleep yet and it's 6 AM here at the time of writing
I will reply when I'm awake

**Comment by mdelaval** [comment]
The `libdiscord-rpc.dylib` file didn't have full read & write permissions, I switched them over and ran them through the different folders again and it's still the same error message. The part that keeps catching my eye is

```
> Error initialising Lua script "discord-rpc.lua":
> [string "/Applications/Aegisub.app/Contents/SharedSupp..."]:13: dlopen(libdiscord-rpc.dylib, 5): image not found
```

Is there something about the `.lua` file that's incompatible with Mac? Is there something in there referencing a `.bll` file rather than `.dylib`? Do you have any semblance of a clue what `image not found` might be about because as you can tell i am very lost lol. My apologies for constantly running into brick walls with this thing, hope you can get some hq rest!

**Comment by mnh48** [comment]
no, there's nothing in the `.lua` file that references `.dll` file, it just calls the library's name which is handled by Lua interpreter in Aegisub itself, which will load `.dll` if it's windows but `.dylib` if it's mac ... the `13: dlopen(libdiscord-rpc.dylib, 5)` part actually tells us that the name it looks for is `libdiscord-rpc.dylib`

I'm reading through https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html

---

can you try to directly download `discord-rpc-osx.zip` from https://github.com/discord/discord-rpc/releases/tag/v3.4.0
and then open the zip file, and then go in `discord-rpc` in the zip, go in `osx-dynamic`, and you will see 2 folders: `include` and `lib`

go in the folder `include` and you will see 2 files, `discord_register.h` and `discord_rpc.h`, copy them

open another finder and go to your home directory, find `include` folder there (it might be hidden, make hidden folder visible if you can't find it), go in that `include` folder and paste the files

---

now go back to the zip folder and go to `lib` folder now and you will see the file `libdiscord-rpc.dylib`, copy it

go to your home directory, find `lib` folder there (it might be hidden, make hidden folder visible if you can't find it), go in that `lib` folder and paste the file

---

after all that, try again from aegisub?

**Comment by mdelaval** [comment]
I put the two `.h` files in `Macintosh HD/Applications/Aegisub/Contents/SharedSupport/automation/include`, would that be the right place? The only other folders named `include` on my Mac are those two from the `.zip` file. When I search my home directory, I can find a bunch of `lib` folders but I checked their enclosing folders and they're all associated with other applications. I even tried creating a `lib` folder within the `automation` folder, next to `include`, but it produces the same error message as the very first post.

There are multiple layers of folders compared to Windows so I wonder where `libdiscord-rpc.dylib` should go in order to work, I think that's where the problem is but I don't know how to solve it. Since you said the Aegisub error description indicates it's looking for `libdiscord-rpc.dylib`, would that mean the persisting issue is where to place that file so it's retrievable by the `.lua` file in `automation`?

**Comment by mnh48** [comment]
no, what I mean is that, the `.h` files should be in `include` folder at your home directory, not in Aegisub ... like `~/include`
and the `.dylib` should be in `lib` folder also at your home directory, like `~/lib`
as the [apple documentation](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html) says that's the place for user libraries, and maybe Aegisub is trying to find it there instead of finding it in their own folder

**Comment by NeSubs** [comment]
Resurrecting this issue.

I'm no programmer, but couldn't you rewrite the script to search in a specific directory for the .dylib? Apple's Developer document seems to imply that it's possible.

>You may also place the .dylib file at a nonstandard location in your file system, but you must add that location to one of these environment variables:
>  •  LD_LIBRARY_PATH
>  •  DYLD_LIBRARY_PATH
>  •  DYLD_FALLBACK_LIBRARY_PATH

**Comment by mnh48** [comment]
from what I read so far, with the way Aegisub loads dependency library (like `.dylib`), it's impossible to define where exactly Aegisub need to look for, because the actual loading of __library__ is handled by Aegisub itself, unlike __normal files__ where it's possible to let user choose where to load from

which is why I can only ask people to put the library (`.dylib` file) on the location that Aegisub is expecting to load from

if someone else could find a way to force Aegisub to load the library from anywhere then please make pull request, because I really can't find the way to do that

**Comment by NeSubs** [comment]
Yeah it's probably pulling from where you're saying it is. Only problem is that a majority of mac users won't have the permissions necessary to add those files into those hidden folders. Even with me fiddling around I still never got my system to allow me to copy the files over to the lib folder.

**Comment by NeSubs** [comment]
Nevermind, fixed it.

Putting it in `~/usr/local/lib` seemed to make it work for me. Running latest version of macOS Big Sur.

**Comment by mdelaval** [comment]
just wanted to log back in on here and say that finding and placing the `.dylib` file in `/usr/local/lib` fixed it perfectly! thank you @NeSubs for resurrecting the issue with the solution and thank you sooo much to @mnh48 for all your help over the months! for instructional purposes, that's the only other step after what's already outlined in the installation readme

**Comment by mnh48** [comment]
is it `~/usr/local/lib` (mentioned by @NeSubs ) or is it `/usr/local/lib` (mentioned by @ilovedaehwi )?
since those two would refer to different places

the one with `~` would be somewhere in the user's directory while the one without will be from root
I will update the instruction after you confirm which one of those two places worked on mac OS

**Comment by NeSubs** [comment]
Sorry that I never responded to this.
I repeated the process on an M1 Mac mini running macOS Monterey 12.1, this time creating the directory /usr/local/lib via Terminal and putting the .dylib there. It works perfectly.
I would suggest using this method instead.

**Comment by mnh48** [comment]
Thank you for confirming it, I've edited the instruction in README to reflect it.
