### ISSUE TITLE
No video file loaded yet

### ISSUE THREAD

**Issue by MSOB7YY** [mnh48/Aegisub-DiscordRPC#2]
it displays "No video file loaded yet" despite the video being opened with [AegisubDC](https://github.com/Ristellise/AegisubDC) version
![IMG_20220517_145055_897](https://user-images.githubusercontent.com/85245079/168815061-92e27363-019b-473e-b5d2-13ea0e46d7ec.jpg)

what i tried:
1. opening subtitles directly > no rpc at all
2. opening video directly > no rpc at all

**Comment by mnh48** [comment]
did you do what the actual instruction said in the README?
specifically the steps in the "Usage" section

**Comment by MSOB7YY** [comment]
> did you do what the actual instruction said in the README? specifically the steps in the "Usage" section

😃😃😃😃😃😃
